Repository patstha/mydotnet, pull requests merged in 2023-10, with the labels that each got.

#36 update nuget packages
  hellobenchamarks/hellobenchamarks.csproj
  tests/tests.csproj
Labels: dependencies

#38 update jdk for sonar
  .github/workflows/sonar.yml
Labels: documentation

#41 use sonar token instead of login
  .github/workflows/sonar.yml
Labels: dependencies

#46 add tests for two sum
  hellolib/TwoSum.cs
  tests/TwoSumTests.cs
Labels: enhancement

#44 add more tests for bubble sort
  tests/BubbleSortTests.cs
Labels: enhancement
